# Site settings
title: 'Срочный выкуп авто в Москве' 
email: 'site email'
phone: '8-926-06-06-444'
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/autoorder/"
url: "./" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
include:      ["*.scss"]
exclude: ["*.sublime-project", "*.sublime-workspace", "*PSD"]
collections:
  articles:
    output: true
  services: 
    output: true

